label: ErrorableCheckboxGroup
status: ready

context:
  componentSourcePath: './ErrorableCheckboxGroup.jsx'
  id: default
  errorMessage: 'This is an error message'
  label: 'Errorable Checkboxes'
  required: true
  options:
    - label: 'Checkbox label'
      value: 'value'
      content: 'a string'
      additional: 'another thing'
    - label: 'Checkbox label'
      value: 'value'
      content: 'some more content'
      additional: 'and another thing'
  values: { key:value }
