label: Side navigation
status: ready
handle: sidenav

context:
  sidenav:
    links: &default_links
      - text: Parent link
      - text: Current page
        current: true
        links:
          - text: Child link
          - text: Child link
            current: true
            links:
              - text: Grandchild link
              - text: Grandchild link
              - text: Grandchild link
                current: true
              - text: Grandchild link
          - text: Child link
          - text: Child link
          - text: Child link
      - text: Another link
