label: ErrorableTextInput
status: wip

context:
  componentSourcePath: './ErrorableTextInput.jsx'
  errorMessage: 'Error message'
  label: 'Label'
  placeholder: 'Placeholder'
  name: 'Name'
  required: false,
  field:
    - value: ''
    - dirty: false
  charMax: 255
