label: Errorable Text Input
status: wip

context:
  componentSourcePath: './ErrorableTextInput.jsx'
  errorMessage: 'Error message'
  label: 'Label'
  placeholder: 'Placeholder'
  name: 'Name'
  field:
    dirty: false
  charMax: 255
